/* Generated By:JavaCC: Do not edit this line. GrammaireLISPConstants.java */
package reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammaireLISPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PO = 5;
  /** RegularExpression Id. */
  int PF = 6;
  /** RegularExpression Id. */
  int QUOT = 7;
  /** RegularExpression Id. */
  int PT = 8;
  /** RegularExpression Id. */
  int IDENT = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\".\"",
    "<IDENT>",
    "<DIGIT>",
  };

}
